### ISSUE TITLE
Theme: Hide new button for pin/unpin navigation menu

### ISSUE THREAD

**Issue by matrix200** [authentic-theme/authentic-theme#1241]
I wish this new icon could be hidden for those of us who don't really care about this new option.
Because of it, now the icons "spilled" over to the second line and I had to remove the refresh button (OCD I know).

**Comment by swelljoe** [comment]
That menu is too crowded, already. It should really be the absolutely *most* important links and nothing else (dashboard, logout, for sure, logged in user, probably...everything else...I'm not so sure).

It's probably time to figure out some other place to put some of these things, so this menu can get back to being small and comprehensible. It's confusing, now. ;-)

**Comment by rostovtsev** [comment]
This is what it shows by default:

![image](https://user-images.githubusercontent.com/4426533/48696651-8f62d780-ebf3-11e8-933a-9afa16bdb2bb.png)

It doesn't overflow. It's configurable and almost any button can be taken away using theme configuration. Aside from configuration, theme extensions will allow you to achieve more.

----

@swelljoe, to add something to navigation menu (button row) is the way to introduce new feature. :wink:  I agree, though, I should have made it configurable.

@matrix200 Do you know that you can change navigation menu width to fit all of the buttons? Check _**Theme Configuration/Navigation menu options/Preferable width**_.

**Comment by swelljoe** [comment]
![screenshot from 2018-11-19 03-15-27](https://user-images.githubusercontent.com/99768/48697268-dd52ed80-eba9-11e8-976c-52f36e24786a.png)

**Comment by rostovtsev** [comment]
@swelljoe This is _**never**_ default as it looks ugly. :smile: 

You can either hide dashboard (called by Alt+I) and refresh (called by Alt+R) buttons or increase navigation menu width a little bit.

**Comment by rostovtsev** [comment]
Sure, why not!

[Added](https://github.com/authentic-theme/authentic-theme/commit/ee8adc346e69856401d9c6d6b6288b449e7461f4).

It will be added to 19.22 very soon.

**Comment by swelljoe** [comment]
@rostovtsev I'm not sure how I got it if it's not the default. I haven't changed anything, as far as I know. ;-)

I'm not much of a tweaker...and that is what the theme looks like on at least some of my systems. I dunno why. I still think it's too busy for the logout/user/whatever icon bar, even without it wrapping around, but I definitely don't like it wrapping.

**Comment by rostovtsev** [comment]
Joe, menu collapse is default for now to let users know about the feature first. With the latest commit you can disable it.

In case you set in the past refresh and dashboard buttons to be visible, then it would break into 2 lines (crowded and not cool)

In case you have these options set since when they were default (2 years ago) 😱 🙂 ..then it's worth resetting to default to see how it is now.. or I would surely recommend disabling displaying Dashboard as a button and refresh too. I also disable now for my self the new  collapse menu button, as all of them can be accessed by hotkey.

But default doesn't wrap, I pay attention to it. It's the way in my screenshot example above.

**Comment by rostovtsev** [comment]
In the future, I will be glad to disable as default pin/unpin (collapse) button too.
