### ISSUE TITLE
Theme: Night mode improvements

### ISSUE THREAD

**Issue by rostovtsev** [authentic-theme/authentic-theme#1249]
It would be interesting to hear a feedback from the users that actively use _night mode_ of the theme! :full_moon_with_face: 

I noticed @lunarovic was using it by the shared screenshots? Anyone else, maybe?

In case you found any issues or would like to share your thoughts on improving it, please post it here.

**Comment by lunarovic** [comment]
![image](https://user-images.githubusercontent.com/2381553/48983672-07e4ff00-f0f2-11e8-85e6-307411a9f92e.png)

The greyed out options are almost invisible. 🌝

![image](https://user-images.githubusercontent.com/2381553/48983661-f865b600-f0f1-11e8-8483-31f54cc5ce19.png)

**Comment by lunarovic** [comment]
@MarkusVolk uses night mode too, seen in https://github.com/authentic-theme/authentic-theme/issues/1242#issuecomment-440296806

**Comment by rostovtsev** [comment]
@lunarovic Okay, thanks. Accepted. If you have more, pile it here.

**Comment by MarkusVolk** [comment]
Yes, I have been using Night Mode for some time now. There's nothing negative that I could say about the design. I think it's really beautiful and I also like the color scheme

**Comment by MarkusVolk** [comment]
Not really an issue, but since you asked for ... perhaps it would be more beautyful to have "yes" in webmin-module-init colored in orange like its done for other modules

![2018-11-30_170717_744637766](https://user-images.githubusercontent.com/6180877/49300419-7941fa80-f4c2-11e8-8551-dfe267f7cc19.jpg)

![2018-11-30_165701_499381787](https://user-images.githubusercontent.com/6180877/49300267-118baf80-f4c2-11e8-89da-5ab45e51d6c7.jpg)

**Comment by rostovtsev** [comment]
@MarkusVolk That's better be done on module side. I will take a look tomorrow.

**Comment by rostovtsev** [comment]
@MarkusVolk Taking a closer look, I must say, that it shouldn't be fixed the way you want it, for the reason, as in _Bootup and Shutdown_ module it's just a **_text string_**, while in _Disk and Network Filesystems_ it's _**the link**_.

**Comment by lunarovic** [comment]
![image](https://user-images.githubusercontent.com/2381553/51372030-1fda6d00-1afc-11e9-9c93-0e7c1567edcb.png)

In "Read user mail", these big white arrows (for skipping to the end or beginning of the message list) do not fit in the dark theme. Also check where else these arrows are used. And I'd argue they do not fit in the normal theme too, because of the size difference compared to the regular small arrows next to them.

While I'm here, there is an inconsistency between these two types of arrows, because these big white ones only appear when there is a need for them (when there is more than one page), but the small arrows are always there, even if there is only one page, and then they are grayed out and not clickable. So I think either the big white arrows should also show all the time (just not in white :D), or the small arrows should also disappear when there is only one page.

(If you don't have many emails to see more than one page, you can go to the module config and change "Mail messages to display per page" to a small number, so you get more than one page.)

**Comment by rostovtsev** [comment]
Agreed and noted! After I finish massive code refactor/optimization (today about to publish first part of it), I will address this issue and few other before releasing 19.23.

Thank you for your feedback!

**Comment by rostovtsev** [comment]
@lunarovic The issue with page arrows was fixed on the commits above.

I am locking and closing this thread. You are welcome to open separate issues.

**Comment by rostovtsev** [comment]
Wrong thread to be locked and closed. Reopening..

**Comment by XhmikosR** [comment]
@rostovtsev: here's a minor issue I noticed with Night Mode using 19.39-2

![2019-09-15_13-43-25](https://user-images.githubusercontent.com/349621/64920338-55d10d80-d7bf-11e9-8454-fe7a384d60bd.png)

**Comment by rostovtsev** [comment]
Hi, it's not just an improvement but a bug.

It's fixed now. Thank you for reporting. :wink:

**Comment by Sopor** [comment]
I have been using computers since 1986. In all these years newspaper, TV and Internet (when it was more available for everyone) have told me that dark background with light letters is bad for your eyes. Now when that generation is gone (almost) and a new younger generation is taking over that never have heard of this, they will now use dark theme. It is harder for the eyes to look at a black background than a white even if you don't experience it that way. That is one of the reasons i hate black keyboards. It is much harder to see the letters on it than a white keyboard with black letters on.
So the battery life (and that it looks beautiful) on my phone will have higher priority than my eyes now when we have OLED screens. Strange development.

**Comment by rostovtsev** [comment]
Interesting. However, it's all personal, and depends on your habits, and even current health of your eyes (overall health actually). 

For example, I code with variation of Monokai theme, and it feels much better/less distracting for me, that the white.

Moreover, there have been formed many false beliefs through the past, like, if you watch TV close enough you gonna lower your eyesight. There are more. It's all prejudices.

Aside from it, there are conspiracies that are made to improve "economics" by selling more. For example, there is a link between getting sick (and further treatment with buying more drugs in pharmacy store/going to the doctor and etc.) and consuming certain products (mostly animal based and cooked; alcohol contained). It's profitable for corporations to create such stories, which people eventually believe. This is why in mass media you can hear things like, "Glass of wine a day, will keep the doctor away", :smile:  or "It's inevitable to drink milk to have strong bones (as there is "a lot" of Ca in it)", or "Eating meat is the only way to get "vital" protein" and etc. and etc.

---

We strayed far off the current issue and far off the subject-matter of this repo. Feel free to email me directly, if you want to continue this discussion.

**Comment by rostovtsev** [comment]
Closing this thicket - there were many enhancements for dark mode theme put in for upcoming 19.42 release. It's way more balanced now.

If you find anything, please feel free to open a new ticket. :heart:
