### ISSUE TITLE
View Logfile: "Toggle Soft Wrap" function?

### ISSUE THREAD

**Issue by 7starsone** [authentic-theme/authentic-theme#1264]
Hello,
the View Logfile at the moment has no word wrap management, so long text is hidden on the line and you should horizontally scroll.

Could you add the _Toggle Soft Wrap_ function as in the File Manager?

Thanks

**Comment by rostovtsev** [comment]
Hi,

It's already available. Either use hotkey (_Command+Shift+W_) or use the menu:

![image](https://user-images.githubusercontent.com/4426533/49655227-28467f00-fa4b-11e8-89b5-889828d8b4d5.png)

**Comment by rostovtsev** [comment]
Try it now.

Hotkey for toggling word wrap in editor and viewer now is set to "Ctrl+Alt+W".

**Comment by 7starsone** [comment]
pardon, if 19.22-beta2 just appears into the settings and not us usual update, what does it mean? Not compatible with....?
here
Webmin version | 1.900
Usermin version | 1.751
Virtualmin version | 6.05

thanks

**Comment by 7starsone** [comment]
it means that I just see that version into the Authentic settings and not into the main dashboard...where I see no update but 
_Authentic theme version_ **19.21** only

**Comment by rostovtsev** [comment]
Yes, because there was a change.

Now, in order to see updates you [need to change config option](https://github.com/authentic-theme/authentic-theme#how-to-show-beta-updates-notifications-for-the-theme) manually. 

Besides, you would want to change caching time in theme configuration to see updates sooner:

![image](https://user-images.githubusercontent.com/4426533/49663609-52566c00-fa60-11e8-82e6-43c0e34c7ca3.png)

**Comment by 7starsone** [comment]
ok, and there (your screenshot) if I force update for beta, if some possible issues about compatibility, does it return that red div with text inside as before?

**Comment by rostovtsev** [comment]
The red warning that you saw in the past, only appears, if the theme that your trying to install, depends on unreleased version of Webmin/Usermin. You must not see any warnings now.

**Comment by 7starsone** [comment]
ok, thanks 👍
