### ISSUE TITLE
Navigation menu color palette - different default color?

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1291]
I was installing a new Webmin and i can see that the `Navigation menu color palette` isn't the same as my old Webmin, but both shows that they are default. Both are running the exact same version of Webmin and Authentic theme. What is correct? Could something be wrong here or is it only a minor glitch?

![image](https://user-images.githubusercontent.com/5789283/52614885-6d47c100-2e93-11e9-8368-416dabd6afef.png)

**Comment by swelljoe** [comment]
Ilia likes White Snow better but he's wrong. (He's wrong not for subjective reasons, but because a bunch of people thought it was a bug when the UI went all white.) ;-)

So, it's almost immediately switched back to Royal Blue as the default, but we haven't shipped a new Webmin version that changed it back yet.

**Comment by rostovtsev** [comment]
@swelljoe Yes, entirely correct!
