### ISSUE TITLE
Clicking the Update Notice twice in quick succession caused screen lockout 

### ISSUE THREAD

**Issue by My-Random-Thoughts** [authentic-theme/authentic-theme#1321]
Installed version 19.32-beta3 and 19.31 (two boxes)

Clicking on the Update Notice button on the main screen loads two copies of the notice screen.  When the top one is closed, the left side bar reappears, but the whole screen still has a "disabled" overlay making it unusable.

The only option is to reload the page.

EDIT: This happens easier on a slow machine, like a Raspberry Pi

**Comment by rostovtsev** [comment]
Interesting, 

I have tried to reproduce it with different network throttling settings and non of them returned an issue. Besides, the speed of the network and machine, shouldn't matter, as the modal and all animations  triggered only after it's getting successful server response.

There is animation mismatch, though, that happens due to recent changes. That I will fix but I have no idea what is happening on your side.

Let's make it clear, you are talking about _Update Notice_ button on the Dashboard? What OS and browser are you using?

**Comment by My-Random-Thoughts** [comment]
Yes, the button on the dashboard, just after the version on the right hand side.  Browser is latest Chrome on Windows 7

**Comment by rostovtsev** [comment]
Is there any chance you could make a video-screencast, so I could see it happening live?

**Comment by My-Random-Thoughts** [comment]
I will when I get back from work (I don't have any software installed for that yet).  In the mean time, here are three screen shots that show the issue.

1st - shows the link I am clicking - it's a slow double-click.  Maybe 1/4 - 1/2 second between clicks
2nd - shows the Update Notice screen (I am sure you have seen this lots of times)
3rd - shows after clicking the X in the top right corner.

![bug_1](https://user-images.githubusercontent.com/21334396/56186160-6dd91100-6016-11e9-82c1-e9e77021c062.png)
![bug_2](https://user-images.githubusercontent.com/21334396/56186163-70d40180-6016-11e9-929c-3ab294deee90.png)
![bug_3](https://user-images.githubusercontent.com/21334396/56186167-729dc500-6016-11e9-8509-547cf22254d6.png)

**Comment by rostovtsev** [comment]
Oh, double-clicks. :smile: Okay, I got it. Thanks.

**Comment by rostovtsev** [comment]
Fixed. Try latest update.

**Comment by My-Random-Thoughts** [comment]
Working perfectly, thank you.
