### ISSUE TITLE
Authentic Falls over to 404 Not Found when "install" is clicked on package installer

### ISSUE THREAD

**Issue by Gizepi64** [authentic-theme/authentic-theme#1346]
I have an issue that seems to only be with Authentic Theme.  Whenever I try to install a package from Apt using the Software Packages Installer, (Pic1) I get a 404 NOT FOUND (Pic3) error after pressing install on the file list (Pic2)
![Authentic404Pic1](https://user-images.githubusercontent.com/8185661/57887800-5fa22e80-7828-11e9-811e-0bada04adfb4.PNG)
![Authentic404Pic2](https://user-images.githubusercontent.com/8185661/57887801-603ac500-7828-11e9-8dbe-ad93dd0cc251.PNG)
![Authentic404Pic3](https://user-images.githubusercontent.com/8185661/57887802-603ac500-7828-11e9-83b8-8fe43a2c9a46.PNG)

If I change the theme back to the old webmin theme the package will install without fault.  I've re-installed my server to try to correct this issue with no luck.  Can you help me with this?

Server is a HP DL160 G6 with 32Gb RAM
OS is Ubuntu Server 18.04.2 LTS
Authentic Theme is 19.34 Beta4

![Authentic404Pic4](https://user-images.githubusercontent.com/8185661/57888060-fec72600-7828-11e9-9ca4-4742317258f0.PNG)

**Comment by rostovtsev** [comment]
Hi,

There was a bug in this regard in Webmin version 1.900.

Please update to the latest Webmin version 1.910.

**Comment by rostovtsev** [comment]
Okay, it's fixed now on the latest dev version.

Please update.

---
It's was the theme bug, that disrespected redirects from progressive output. It was introduced due to making browser history work with progressive pages. It was very very tricky part to implement correctly. 

Sorry about that.

We will release new theme version in few days and new Webmin version to address this and few other ongoing issues.

**Comment by Gizepi64** [comment]
:)

Looking forward to seeing it fixed.  Thanks for your time.

Ian

------ Original Message ------

**Comment by rostovtsev** [comment]
Ian, you can already update it to latest development version, using theme configuration.
