### ISSUE TITLE
File manager: search

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1349]
If i search for something it will show up like this:

![image](https://user-images.githubusercontent.com/5789283/57938874-63d25880-78c9-11e9-9927-b798cbe14f48.png)

And to close it there is a red circle (if i hover the mouse pointer over it) with an X inside to close it with but it seems that i can press on the word too. I don't know if this can create any problems? I only assumed that i was forced to press on the red X to close it, but obvious not ...

If i press with the right mouse button on it this will popup, so I also wondering what this is?

![image](https://user-images.githubusercontent.com/5789283/57939487-c2e49d00-78ca-11e9-8faa-d1f7a1f501d8.png)

**Comment by rostovtsev** [comment]
It's some bug. It shouldn't appear in search mode at all. I also discovered that this broken path popup only appears if search was in root folder.

I don't know how did you discovered it but good job. :grinning: 

-----

By design, when right clicked or hotkey Ctrl+L is clicked, the popup comes up, letting you enter path manually.

![image](https://user-images.githubusercontent.com/4426533/57965129-560fe800-7948-11e9-8d39-0b1edf551a8e.png)

**Comment by rostovtsev** [comment]
Okay, it's been fixed. Thanks.
